development:
  adapter: postgresql
  encoding: utf8
  database: webpage
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: webpage
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: webpage
  pool: 5
  username: 
  password: